### ISSUE TITLE
Redesign: Keep certain functions always visible

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#102]
Examples are: [ Add User ], [ New Issue ], [ Add Tag ] and so on...

**Comment by satrun77** [comment]
What this issue is for?

**Comment by nickbe** [comment]
Just a reminder to keep certain buttons from scrolling out of view in later (redesigned) versions.

**Comment by nickbe** [comment]
Obsolete. Redesign templates are coming anyway.
