### ISSUE TITLE
Error in Kanban view

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#106]
I just created a ticket as manager.
Then I set the status to OPEN. OPEN has a limit access of DEVELOPER. The ticket is assigned to the developer.

Now the developer logs in . Since the kanban is configured to show the OPEN status the issue should show up. But I receive an error message as soon as I try to select the project in the kanban:

ErrorException in line 72: Trying to get property of non-object (View: resources\views\user\issues-kanban.blade.php)

**Comment by nickbe** [comment]
Ok. Now I can see kanbans again.

One suggestion though since I'm currently testing the tag role limits.
When a user has no right to change a state in the kanban can we simply prevent him from dragging an issue around in the first place? OR Snap the issue back to where he started and show some inline error message?

**Comment by satrun77** [comment]
> Can we simply prevent a user from dragging an issue around in the first place if he has readonly access to the current state or if he's trying to set a state where he has only Read access? (Like snapping the issue back to where he started and show some inline error message?)

If this is an issue can you please creates new record for it :)

**Comment by nickbe** [comment]
Sure can do :)
