### ISSUE TITLE
Readonly flag in tags

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#107]
The readonly flag works so far and trying to edit a protected issue shows:

No no no, not this page.
Server Error: 401 (Unauthorized) 

I think its better to disable the edit button/function in this case.
(Maybe show a small 'lock' icon)

**Comment by satrun77** [comment]
The hover effect can be fixed in the new design :)

**Comment by nickbe** [comment]
You're definetely right there :)
Biut could you replace the error message with something more subtle like a message box?

**Comment by satrun77** [comment]
The 404 and 401 errors returns randomly selected message. This can be improved with the new design

**Comment by nickbe** [comment]
You mean with proper message windows?

**Comment by satrun77** [comment]
It is display related change and would be better to wait for the new design, then can show messages in more friendly way

**Comment by nickbe** [comment]
Oky :)
