### ISSUE TITLE
New error when sending mails per queue

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#108]
The command: php artisan tinyissue:messages
results in:
[ErrorException]
Trying to get property of non-object

Attached is my current message queue.

[queue.zip](https://github.com/satrun77/tinyissue/files/336983/queue.zip)

**Comment by nickbe** [comment]
Any idea yet why this is happening all of a sudden?

**Comment by satrun77** [comment]
I have not looked into this yet.

**Comment by nickbe** [comment]
Looks good. So far I had no more errors and lots of messages ;)
Thanks and closed.
