### ISSUE TITLE
Creating new issues

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#11]
1. What do you think about relocating the '+ New Issue' button to the right side of the top header, and left of the menu button when it appears? 
2. Probably the thing that bothers me most is that I cannot edit an issue. At least I have no idea how.

**Comment by satrun77** [comment]
Can you please provide a screenshot?

**Comment by nickbe** [comment]
*laugh* I just found out how to edit an issue. I think the mouse over to edit an issue is terrible - now I remember this from the original tinyissue :)

As for the New Issue button location... see attached
![Uploading Unbenannt.jpg…]()

**Comment by satrun77** [comment]
Most of the features are from the original project. I kept everything and added more features. I'm open for any changes and improvements. 

Also, feel free to help with pull requests.

**Comment by nickbe** [comment]
I know. What if I offer to create a little website for your project :D ?

**Comment by nickbe** [comment]
Wrong post. The website was meant to go into a new issue topic.

**Comment by nickbe** [comment]
Closed for now. There are more important things to do.
