### ISSUE TITLE
Bug when editing/saving tags

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#110]
While showing the system to a colleague today I noticed that we got a "Whoops" error message when editing/saving a tag. I didn't notice this yesterday so I'm little bit uncertain about that. Could you check this please?

**Comment by satrun77** [comment]
Unable to replicate this. Make sure your database is upgraded.

**Comment by nickbe** [comment]
Sorry, I'm an idiot. I realized that I forgot to update the database and solved the problem already yesterday. Then I forgot to cancel the github issue.
Again sorry!
