### ISSUE TITLE
ADMIN: Show a clear indicator in the UI when site is marked as down

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#113]
... maybe you should give the admin a simple button to set/reset this site down file flag directly without searching in the file system.

**Comment by nickbe** [comment]
It seems that I can mark the site as down, but then I can login and work anyway.

**Comment by satrun77** [comment]
Only admin user can log in when site is down. Other users should not be able to login.

**Comment by nickbe** [comment]
:-D I didn't test it that way.
Of course it works.
(And I really like the offline message)
Thanks.
and closed!
