### ISSUE TITLE
Enforce role access and readonly for list and kanban

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#116]
If an issues status access role limit forbids it then it shouldn't be able to see the issue in the first place. Neither in the list, nor in the kanban. This way the newly invented ReadOnly tag setting makes most sense then.

**Comment by satrun77** [comment]
Can you please provide more details here.

**Comment by nickbe** [comment]
Sure, let's say an issues status is "BACKLOG" 
and the **BACKLOG**s role access limit is "Developer".
and the **BACKLOG**s readonly role is "Developer".

This would mean that the **user** who created the issue can see it in lists or kanbans but he cannot edit the issue since it's now readonly due to the **BACKLOG**s readonly role. 
-> So being the owner overrides the role access limit, but NOT the readonly role.

Other users cannot see the issue in the lists or kanban because of the **BACKLOG**s role access limit.

A developer CAN SEE the issue but he cannot edit it because of the readonly role.

**Comment by satrun77** [comment]
This is currently working as its described here. The only thing not implemented is the user able to edit the issue created by the user (There is another issue tracker for this).

**Comment by nickbe** [comment]
Seriously? :)
This is how private/public works? I'm on holiday for 3 days now. When I'm back I was told we get the new design samples and I'll have the time to check out the private/public thing.

**Comment by satrun77** [comment]
Private projects:
User role: cannot see any private projects, unless the user is part of the project team, then this user can add issue and view project issues.

Public projects:
User role: can see any of the project issues. 
Not logged in user: can see any of the project issue.

Your issues view (List and Kanban):
User role: see issues the user created. 
Developer/Manager/Admin: see issues that are assigned to them.

**Comment by nickbe** [comment]
In a private project normal users should not see issues created by other users. Only the ones they created themselves.

Is this the way it works?

In a private project I don't want a bug reporter (user) see the bugs reported by other users.

**Comment by satrun77** [comment]
Users that are not part of the private project don't have access to create issues. The project is private and they are not part of the project team. I cannot see the point of allowing anyone of creating issues to a project they don't have access too.

To private and public projects,  you have to be granted an access to the project to be able to create issues.

Public projects means issues and discussing is publicly opened to all users event not registered users.

**Comment by nickbe** [comment]
So I what I mean is there should be an option to have a "closed" private project. So when one user reports an issue, others are not allowed to see this. Basically every user should see only his/her only issues. 
(But you already asked the right question on gitter the other day)

**Comment by nickbe** [comment]
I'll close this issue too.
Moving to the user role discussion issue now.
