### ISSUE TITLE
ROLES: Restrict issue list for user role according to private/public flag of project

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#121]
I think we should restrict issue access for normal users depending on the private/public flag of the project (which we already have). Since this flag already does something similar to the project itself.

That way we can control if a project is really public (like an OpenSource project where everyone can see what's happening) or more company internal (where issue reporters like clients or testers should only see what they've created)

**Comment by satrun77** [comment]
Can you provide more details here. How do you want to use the project flag and issue access?

**Comment by nickbe** [comment]
Ok I described that in #116

**Comment by nickbe** [comment]
I just tried the "internal" feature. Right now it seems that my user2 does still can see issues created by user1 in the listview of a project.

**Comment by satrun77** [comment]
I'm unable to replicate the issue in your last comment. I have setup a projects (Internal) with issues created by manager, user 1, & user 2.

If I login as Manager ==>  I see everything.
If I login as User 1     ==> I only see issues created by the user 1.
If I login as User 2     ==> I only see issues created by the user 2.

**Comment by nickbe** [comment]
That's weird.  I just tried that with the latest 2.10.
When we go to 'Projects' -> Active Projects -> <OurProject> -> then on the right side to "Open Issues" -> here you see all issues. No matter who created it or what status they are in.

**Comment by satrun77** [comment]
Can you post some screenshots of the users profile details, project edit form and open issues page to compare with what I have.

**Comment by nickbe** [comment]
I'm moving my demo instance online. But when I did it I receive this error after deleting an issue:

FatalThrowableError in QueueTrait.php line 73: Call to a member function isOpen() on null

**Comment by satrun77** [comment]
The above issue should be fixed in develop-2.10 branch

**Comment by nickbe** [comment]
Works again. Thanks.

I'm doing several things right now: Providing a test instance for both of us under develop.tinyissue.org, finishing the first draft the tinyissue webpage, working with helmut on the design.

**Comment by nickbe** [comment]
Closed for now. Further issues should be treated seperately.
