### ISSUE TITLE
Is this configuration completely possible at the moment.

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#123]
Currently we're trying to handle certain software projects with these status steps.
So this might as well be a test case for you.

NEW, BACKLOG, DISCUSS, OPEN, WORKING, REVIEW, RELEASE, ABANDON

First the issue is **NEW**. (Developers should not see those at all. Not in the list, not in the kanban)
Then the manager decides what to do:
  - If the issue is valid and should be resolved it is set to **OPEN** 
    (Now developers can see the issue)
  - If the issue is valid to meant for later he sets the status to **BACKLOG** 
    (Developers cannot see it)
  - If the issue is valid but needs discussion first then the new status is **DISCUSS**
    (Developers can see it but are only allowed to comment, but not change the status or resolve)
  - If the issue is not valid then he sets the status **ABANDON** 
    (Developers cannot see it here. It's up to the developer to close, delete or comment the issue first)

**Comment by satrun77** [comment]
Did you manage to implement this setup? if not, which part failed?

**Comment by nickbe** [comment]
Right now it seems that I cannot create the DISCUSS step. I don't think I can let the developer see the issue, comment the issue, but at the same time prevent him from changing the status.

**Comment by satrun77** [comment]
I have not tested this.

The DISCUSS tag here is readonly for developer, which makes the issue.
- Visible
- When developer edit the issue, the form is visible with message "Issue read only" and no buttons to save.
- The developer should be able to add comments.
- Changing the status from Kanban view, will not be saved. I think there might be newer change to make the item not draggable with lock icon.

Do you have the latest code from develop branch?

**Comment by nickbe** [comment]
Not yet. I'll try that as soon as possible.

**Comment by nickbe** [comment]
After updating I currently get this error:

ErrorException in AliasLoader.php line 66: 
Class 'Collective\Html\FormFacade' not found (View: U:\Seafile\Workspace\GravSites\www\tinyissue77dev\resources\views\user\login.blade.php)
Did I do something wrong?

**Comment by nickbe** [comment]
Also I just noticed this message when running composer:

Package caouecs/laravel4-lang is abandoned, you should avoid using it. Use caouecs/laravel-lang inst
ead.
Package illuminate/html is abandoned, you should avoid using it. Use laravelcollective/html instead.

I could've sworn your had that already fixed last time or did you?

**Comment by satrun77** [comment]
Make sure you have pull the latest changes from git.

```
$ get fetch --all
$ git pull origin develop

```

**Comment by nickbe** [comment]
I downloaded a fresh develop version but it didn't do it.

**Comment by satrun77** [comment]
Package illuminate/html is not longer in the composer file. It was replace with:
https://github.com/satrun77/tinyissue/blob/develop/composer.json#L14
The page caouecs/laravel4-lang also replaced with the newer version.

**Comment by nickbe** [comment]
I try to redownload a fresh develop package and try again. This should contain the latest commits or do I have to download additional files?

**Comment by satrun77** [comment]
All you need it get the latest code from repository and then execute the composer command.

**Comment by nickbe** [comment]
after composer update I receive this error now:

Script php artisan clear-compiled handling the post-update-cmd event returned with an error

  [RuntimeException]
  Error Output:

After that all I see is a when running the website is a blank white page

**Comment by satrun77** [comment]
Try executing this
`php artisan clear-compiled`
or 
`composer update`

**Comment by nickbe** [comment]
Yep. Just tried that. Still ending up with 

Script php artisan clear-compiled handling the post-update-cmd event returned with error code 255

**Comment by satrun77** [comment]
Make sure the following directory writable:
`storage/ & bootstrap/cache`

Clear everything in `bootstrap/cache`

**Comment by nickbe** [comment]
After clearing bootstrap/cache I'm back to:

ErrorException in AliasLoader.php line 66: Class 'Illuminate\Html\FormFacade' not found (View: resources\views\user\login.blade.php)

**Comment by nickbe** [comment]
Ok. tried everything again... fresh install... copying the database and .env from my previous installation along with the config/mail.php, checking the path to my database. Everything similar to my working test instance. Deleting the bootstrap/cache,  php artisan clear-compiled,  call composer update --with-dependencies, php artisan migrate...
Still the error message remains.

**Comment by satrun77** [comment]
I don't know why you are getting these errors. I can't replicate your errors

**Comment by nickbe** [comment]
Ok. after doing everything over again I managed to get it to run after starting 'composer update --with-dependencies' a second time. Very strange!

Also simply updating the already existing instance does not work anymore. Which is also odd since I did this countless times before and never had a problem.

**Comment by nickbe** [comment]
I've tried updating the existing instances just now again, but it's no good. 
There must be something else that has to be cleared or deleted when updating. Wouldn't it be possible to have some 'all in one' commandline update routine, which could then be called from within the GUI later on.

**Comment by nickbe** [comment]
Can you tell me what difference there is between updating an instance and a fresh install (and copying .env and database)? Which folders would I have to clean manually when updating?

**Comment by satrun77** [comment]
Source code update you need composer
`composer update`

Database update you need laravel migration command
`php artistan migrate`

Something is not working with your environment?

**Comment by nickbe** [comment]
Maybe the problem lies with the cache folders. I don't know exactly how laravel works in depth but it seems there's a fair amount of caching going on. So maybe I could delete the cache manually next time.

**Comment by nickbe** [comment]
I will play through various scenarious during the weekend now. 
Thanks upfront for all the latest commits :)

**Comment by nickbe** [comment]
I think basically it's possible to build these kind of workflows now.
I'll close the issue and we move further thoughts to the same github issue where we write down the user role descriptions.
