### ISSUE TITLE
QUESTION: What happens if I delete a tag which is or was in use in one or more issues

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#124]
...or a user who is or was assigned to an issue?

**Comment by nickbe** [comment]
Another thought: How do tag role limit generally override each other? The old "Restrictions before permission" rule?

Example: Issue is tagged with status "WORKING" (developer has access here) and at the same time with type tag "NONSENSE" (developer has no access here)?

**Comment by satrun77** [comment]
Tag removed and references to also removed from the issues. For example, if you remove type tag "Bug" then all of the issues that uses this tag would no longer have a type tag selected.

**Comment by nickbe** [comment]
Ok. I made a different mistake when I tested this. Everything's of course all right and I just got an issue with no status or type. 

But then if I delete a project - Are the referring issues deleted with it? (As one would of course expect). Just asking :)

**Comment by satrun77** [comment]
It will delete everything related to the project.

**Comment by satrun77** [comment]
Delete project will delete everything in the project (issues, comments, ...etc)

**Comment by nickbe** [comment]
Ok. Thanks.
