### ISSUE TITLE
BUG: Dropdown for adding users show deleted users as 'Anonymous'

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#126]
My database contains lots of deleted users. 
Is it in fact necessary to retain deleted users at all?

**Comment by satrun77** [comment]
This is part is still based on original project. The users should not be visible to anyone, they should not be able to login. But kept in database because they may have other related data (ie. added comments, issues, ...etc).

**Comment by nickbe** [comment]
Ok.  I suggest we simply delete them then - along with all references as owners or commentors and display missing references as "Anonymous" instead.

**Comment by satrun77** [comment]
Not sure I understand.

**Comment by nickbe** [comment]
I think deleted users should be deleted for good and not marked as deleted. 

With them you should also remove the references to those users.

**Comment by satrun77** [comment]
Then you loose everything they have done. We have developers joining the company. Work on issues make comments and upload files .... When these developers leaves the company, if we delete everything they have done, then we loose all the info.

You need the database records, it just need to be not selectable.

**Comment by nickbe** [comment]
When logged in as manager and assigning users to a project I see lots of anonymous entries.
I do think a manager should always see a complete list of names without any reference to the public status of a user.

**Comment by nickbe** [comment]
Looks good now. Thanks and closed.
