### ISSUE TITLE
BUG: Issue owner not recognized when creator is logged in

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#128]
Test Platform: 
The Issue "The software does not work on mondays" is shown as labelled "by Anonymous" when the user who created the issue is logged in. So he's also not able to edit the issue anymore.

**Comment by satrun77** [comment]
Logged in user with "User role" cannot edit issues even if they created the issue.

**Comment by nickbe** [comment]
I think users should be able to edit their own issues as long as their tags allows this.
So for example if I post an issue and its initial status is NEW then I should be able to edit the issue as long as NEW has a role access limit of USER and no readonly. 

Then after moving the status of the issue to OPEN (which has a role access limit of MANAGER and a readonly of USER) I should not be able to edit the issue anymore.
 
I think that the tag system makes it perfectly possible to decide when a user can edit his/her own ticket and when not.

**Comment by nickbe** [comment]
Please see #39. according to my own notes editing your own ticket must have been already possible then.

**Comment by nickbe** [comment]
I close this issue report single problems in detail when I encounter them.
