### ISSUE TITLE
Error after upgrading to latest develop version

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#129]
Just tried the latest develop version (upgrade and also a clean install)
Both show this error after login:

Call to undefined method Illuminate\Database\Query\Builder::dataCollection() (View: resources\views\activity\update-issue-tags.blade.php) (View: resources\views\activity\update-issue-tags.blade.php)

**Comment by satrun77** [comment]
This should be fixed now. I accidentally removed the method dataCollection()

**Comment by nickbe** [comment]
Thanks and closed.
