### ISSUE TITLE
Cannot see issues even if I'm manager/admin and part of the project

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#130]
In the online test instance, I login as either manager (Chief Andy) or admin (Master Colin).
The project "Closed development client project" should come up with 3 issues in the "Open issue" list but I cannot see any of them.

Please correct me if I'm wrong but I think a manager (or admin) should always have access to all the issues in the issue list "Open issue", since he's the one who must be able to assign, revoke or edit the issue at all times.

**Comment by satrun77** [comment]
I think you don't have the latest code from develop branch.

**Comment by nickbe** [comment]
I did a clean install around 5 hours ago. I deleted all the folders except my public/debug subfolder and the database file inside /storage. Everything else was freshly installed to my best of knowledge. So no cache folder should have remained.

I've just sent you the account for accessing the folder via mail.

**Comment by satrun77** [comment]
I found the problem and fixed it.

**Comment by nickbe** [comment]
Ah ok. Thanks. 
I'll continue to check out the whole tag role concept and try to close several issues.

**Comment by nickbe** [comment]
Yeah this looks good also now.
Thanks for fixing. Closed.
