### ISSUE TITLE
An other fork is still alive

### ISSUE THREAD

**Issue by Patriboom** [satrun77/tinyissue#138]
You can follow the fork [https://github.com/pixeline/bugs](https://github.com/pixeline/bugs)  which offers lot more options and capabilities than the original one.  I don't know what more or less against this (saturn77/tinyissue), but ... I made changes again today on pixleine/bugs.

The [https://github.com/pixeline/bugs](https://github.com/pixeline/bugs) fork has worked with other projects so it can now generate reports.  Come and see.

**Comment by satrun77** [comment]
This project still alive. I’m working on it when I have free time. However, the last few years it’s been very busy have not done much. Feel free to contribute with pull requests.

This fork created before the other fork mentioned in the ticket and code base changed a lot from the original project. It’s still the same look and feel, there are more features.
