### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#16]
I hereby humbly suggest to rename the project to 'TINY ISSUE BOARD'.
And this project really deserves a proper website.

**Comment by nickbe** [comment]
New logo humbly attached :)

[layout.zip](https://github.com/satrun77/tinyissue/files/173689/layout.zip)

**Comment by satrun77** [comment]
Thanks for the interest of the project. I like the name Tinyissue and prefer the project name to be short :)

**Comment by nickbe** [comment]
Well, I think it's important that people recognize the difference between the original fork and this one. And as I said I'd like to contribute a homepage for this if you like. 

Then I would just add the word "board" in a different (darker) color to enhance the original connection
So it's the TINYISSUE Board - Edition :)

**Comment by satrun77** [comment]
I'm ok with creating a homepage. Can you please create another issue or pull request to discuss everything involving the homepage. 

You do have a point there about the name. Create a mockup of the new homepage and we can go from there to discuss the project name and other details.

**Comment by nickbe** [comment]
All right then :)
I'll create a homepage draft and send you a link with htaccess user/pass.

**Comment by nickbe** [comment]
Just a thought that crossed my mind while working on the homepage draft...
What do you think about the name "issueboard". It's short. There's the word 'board' and there's the 'issue', and when the app becomes more advanced and streamlined it might still be small and easy to handle, but it's not that tiny anymore. So ISSUEBOARD would fit rather nicely, don't you think :D ?

**Comment by satrun77** [comment]
What do you mean by the word 'board'?

I like the original Tinyissue because it is simple, and does not include many features. I like to keep the same principle. 

I even thought about keeping the app simple by default (ie. no kanban) with option to install add-ons. Then the app simple 'Tiny' by default. Unfortunately, I don't have time to plan and build.

**Comment by nickbe** [comment]
I thought about the term "kanban board" and thought it could be combined. I understand that you like to keep simple. So do I. Most systems like osTicket and others and too heavy with far too many features, so that configuring alone can take you days. Others were too simple and not able to handle basic needs. 

What I like about tinyisse, and in this case especially this project, that you tried to enhance a basically simple system. and if you like the name then that's ok for me. I'm always trying to be creative and things like this came up just by itself :)

Also I'm trying to maintain an installation of the open source project kanboard for our team. But it suffers from the same problem. It's too much. too complicated. And none of the others likes the way it works and the way it looks.

Right now I think I nailed everything in the issues that I was missing in the other systems or in the old tinyissue. 

You kanban implementation is genius and I mean it. The way normal ticket systems work you simply have no real overview on what is going on. That's why I always wanted a kanban board, but no complicated systems or even worse multiple systems.

So I'm happy with your decision about the name. And I'l try not do make things overcomplicated. I promise. On the contrary - I will do my best to make the visual appearance simpler, like for example the issue history.

I'm just trying to find a better way to display issue details, also I drafted a proper tinyissue icon - and I just used the name "tinyissue", because I knew you'd like that most.

**Comment by satrun77** [comment]
Creativity is important I agree :) 

I would like to fix all of the existing issues first. Then work on improving the user interface, including finding a new name to differentiate it from the original project.

**Comment by nickbe** [comment]
Fully agreed :)  - step by step is always the best way.

**Comment by nickbe** [comment]
Deferred until otherwise decided. First function, then maybe name discussion.
(To be honest I've began to like TINYISSUE :)
