### ISSUE TITLE
Kanban and tickets

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#19]
This is more a personal wish, but I saw a kanban board with user icons on the right side of the ticket.

![unbenannt](https://cloud.githubusercontent.com/assets/10890765/13774356/e11211a8-ea9e-11e5-8735-2a5cdb2827cf.jpg)

When working in a team like me, this is not only a nice touch - it's also really helpful.

**Comment by nickbe** [comment]
Actually this is what I would really wish for :) 

![unbenannt](https://cloud.githubusercontent.com/assets/10890765/13790579/7afd3172-eae9-11e5-9fe0-b617acdc62a6.jpg)

Depending on the type of Ticket (Bug, Feature, Idea) the colored stripe on the left would then shows the color accordingly.

**Comment by nickbe** [comment]
Also in this view you have to select the project from a dropdown.

I suggest you just show them side by side as link-buttons and collapse them to a dropdown when then screen gets smaller.

**Comment by satrun77** [comment]
> I suggest you just show them side by side as link-buttons and collapse them to a dropdown when then screen gets smaller.

Can you provide screenshot or mockup?

**Comment by nickbe** [comment]
Let me play around with the kanban board and it's css to get a little bit more used to the laravel environment. I'll try to do this directly in my fork and show you :)

**Comment by nickbe** [comment]
Just trying to enhance visuals a bit...

![screenshot_14](https://cloud.githubusercontent.com/assets/10890765/13951228/d96a91a0-f02f-11e5-900d-7fbbf6414883.jpg)

i also think we should replace the current image buttons with pure css buttons.

**Comment by nickbe** [comment]
I made a first draft of the project selector and the new kanban layout.

![screenshot_15](https://cloud.githubusercontent.com/assets/10890765/13960369/5cda198e-f058-11e5-82a4-6653d53e0e11.jpg)

Also I create a pull request for this, so you can check this out.

**Comment by nickbe** [comment]
All right then. This is what the kanban board looks like at the moment.
If you agree then I'll try to initiate multiple pull request now.

![screenshot_16](https://cloud.githubusercontent.com/assets/10890765/14001605/2919113c-f147-11e5-8c96-b3bb29f8d8f9.jpg)

**Comment by satrun77** [comment]
This looks good. 

How would you display many projects in the desktop view? I have about 20 open projects in my instance of Tinyissue.
![2919113c-f147-11e5-8c96-b3bb29f8d8f9](https://cloud.githubusercontent.com/assets/166450/14002424/de6960e6-f1b0-11e5-8f79-1a081062e48f.jpg)

**Comment by nickbe** [comment]
For now you should see the dropdown when the quick project bar becomes too wide.
Right now I can fit around 10 Projects on the bar until they collapse into the dropdown.

(btw. I even think the words "Choose project" are not essential here and could go)

So for you nothing much changes here. 

But i had the idea to mark projects as "Favorites" and then maybe just display the favorites in the quickbar.

**Comment by nickbe** [comment]
My first pull request... was a bit of a mess I guess.
Big thanks and closed.
