### ISSUE TITLE
How do public projects work

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#21]
Shouldn't it be possible to skip the login and just view the public projects? Or am I interpreting something wrong here? What exactly are public projects?

**Comment by satrun77** [comment]
Public project does not skip the login. It just means you can display specific project to everyone. The following pages are accessible to display public projects only:
https://bug.my.geek.nz/projects
https://bug.my.geek.nz/issues

**Comment by nickbe** [comment]
Can you give me the login data for this sample?

**Comment by satrun77** [comment]
This is my personal instance of tinyissue. I use Tinyissue to manage my personal projects. :)

From your instance take the following steps:
1. Administration settings >  Turn public projects on.
2. Create a new project with status public.
3. Open http://yousite.com/projects
4. You will see the public projects and other information.
5. This feature is based on a pull request from the original project.

**Comment by nickbe** [comment]
Okaaaay. I wasn't aware of this feature at all. But it perfect and exactly what I thought it should be.
Thanks and defintely closed.

**Comment by satrun77** [comment]
The project do lack documentations. I just don't have time to do that. Maybe if the we have a homepage for the project we can include documentations, ...etc :)

**Comment by nickbe** [comment]
Very good idea.
Also maybe it's also possible to reorder some of the current functions in the GUI. I think this would help. Along with some css enhacements :)
