### ISSUE TITLE
Error when creating issue from within project

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#22]
If you're on the dashboard and you click [+ new Issue] then everything works fine,
but if you've selected an project and you're inside the project list, then [+ new issue] throws and error:

![screenshot_11](https://cloud.githubusercontent.com/assets/10890765/13791194/3226d914-eaec-11e5-9542-9ffe925b1e09.jpg)

**Comment by satrun77** [comment]
I only managed to replicate the issue when the project ID in the URL was incorrect. 

The URL structure for adding new issue is ` /project/[project ID]/issue/new`

**Comment by satrun77** [comment]
I think I managed to replicate this issue. Fixed in `develop` branch

**Comment by nickbe** [comment]
The problems seems still to be there. This is the URL.
While this works: http://localhost/projects/new_issue
This won't:  http://localhost/project/1/issue/new

**Comment by satrun77** [comment]
This is also related to the route configuration when public project is enabled.

**Comment by nickbe** [comment]
I tried yesterdays version which still seems to have the problem. I wanted to translate, but I couldn't see the translated tags there. Have you already located the problem?

**Comment by nickbe** [comment]
Yep. works now. 
Thanks and closed.
