### ISSUE TITLE
Error when trying to delete a tag from the kanban board

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#23]
There's an issue in the same status as the kanban column I want to delete, but then this should work. I only want to delete the column and not the issue.

**Comment by satrun77** [comment]
I may have fixed this issue but not sure. The code change in `develop` branch.

**Comment by nickbe** [comment]
Ok I'll recheck this tonight

**Comment by nickbe** [comment]
Oh boy... I must've been really tired when I wrote the gibberish above. what the hell?
Anyway :) Seems to work now.
Thanks and closed
