### ISSUE TITLE
Just a question when updating

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#24]
In the past I once hit a point where I was stuck with an error when starting, after I updated the files.
But although I didn't overwrite the database I never found out what happened and had to reinstall.

What is the proper way to update to a new release?
What can I overwrite and what not?

**Comment by satrun77** [comment]
Upgrade steps
1. With git command line. Pull latest changes `git pull origin master'
2. Run composer update `composer update' to install any dependencies
3. Execute Laravel migration command `php artisan migrate` to update the database.

**Comment by nickbe** [comment]
Well, I'll have to learn about using git. Since I'm mostly on windows when testing I'm not used to it.
But I'll promise to do my homework o_O

**Comment by satrun77** [comment]
You don't need to learn git if you don't want. 

Steps without get:
1. Download zip file of latest code from github.
2. Backup the `storage` directory.
3. Replace all other files.
4. Run composer updatecomposer update' to install any dependencies.
3. Execute Laravel migration command php artisan migrate to update the database.

**Comment by nickbe** [comment]
Great. Thanks a lot. :)

**Comment by nickbe** [comment]
It works if I use: composer update --with-dependencies.
Otherwise 'php artisan migrate' fails.

**Comment by nickbe** [comment]
When updating with:

composer update --with-dependencies

I get this right at the end:

```
> php artisan clear-compiled
X-Powered-By: PHP/4.4.9
Content-type: text/html

<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>/kunden/blue-group.de/webseiten/my.couchticket.de/artisan</b> on line <b>34</b><br />
<br />
<b>Parse error</b>:  syntax error, unexpected T_STRING in <b>/kunden/blue-group.de/webseiten/my.couchticket.de/artisan</b> on line <b>34</b><br />
Script php artisan clear-compiled handling the post-update-cmd event returned with an error


  [RuntimeException]
  Error Output:
```

So far tinyissue seems to work anyway. But it might be better to know the reason for this.

**Comment by satrun77** [comment]
The error is with Laravel core code. 
>-Powered-By: PHP/4.4.9
Are you using PHP4? if you are, then this is the problem, Tinyissue will not work in php4.

**Comment by nickbe** [comment]
No. PHP -v says: 
```
PHP 5.6.12 (cgi-fcgi) (built: Dec 26 2015 15:35:35)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

**Comment by satrun77** [comment]
Line 34 https://github.com/satrun77/tinyissue/blob/develop/artisan#L34
Error message "Unexpected character in input:  '\'" 
There is nothing wrong here. The "\" is new syntax not available in older version of php. I think for some reason your environment is using php4 to execute artisan script

**Comment by nickbe** [comment]
Strange. If you enter: **php artisan** the last line says.
```

X-Powered-By: PHP/5.6.12
Content-type: text/html; charset=UTF-8

```

**Comment by nickbe** [comment]
Ah you meant the composer is running on 4.x.
Well I have no idea how this happens.

**Comment by nickbe** [comment]
It's definetely PHP 5.6.x

Beste Grüße | Best regards
Nicolaus Berglmeir

A L L G Ä UINFORMATIK®GMBH
Lindauer Str. 4, 87439 Kempten, Germany
+49 831 20699 800(tel:+49%20831%2020699%20800)• home@ai-support.de

Geschäftsführer: Nicolaus Berglmeir, Markus Neri • Vertretungsberechtigt: Lothar Hinz • DE281261678 • Sitz u. Registergericht: Kempten • HRB1363
Inhalt ist vertraulich / Content is confidential


Am 14. Juni 2016, 22:47 +0200 schrieb Mohamed Alsharaf<notifications@github.com>:

**Comment by nickbe** [comment]
I think this should be closed for now. If there's an automatic update function one day then the better. But it seems there's nothing more to do here.
