### ISSUE TITLE
Date format in global settings

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#25]
I suggest replacing the manual date format field (and a reference to PHP)
(which is really not very userfriendly :)  with a simple dropdown box and
a list of the most common date/time formats selectable as examples in the 
dropdown.

**Comment by satrun77** [comment]
what date formats would you like to see here?

**Comment by nickbe** [comment]
I think there are basically a few that are most commonly in use:

1. April 2016  16:23 
Mi, 1. April 2016  16:23
2016-04-01  16:23
April 1st, 2016  4:23 pm
4/1/2016  4:23 pm
Wed, April 1st 2016  4:23 pm
01.04.2016  16:23

But if course add those you think are missing here. I wouldn't provide too many but I think it's a nice personal touch for the user settings.

**Comment by nickbe** [comment]
Nice :)
As always a big thanks and closed
