### ISSUE TITLE
Simple 'user' should not be able to assign a ticket nor set it's status.

### ISSUE THREAD

**Issue by satrun77** [satrun77/tinyissue#28]
Simple 'user' should not be able to assign a ticket nor set it's status.

He should however have a seperate field to state the tickets 'type'. I don't think the current Tag system is usable that way. Having simple dropdowns per ticket with a 'resolution', a 'Current Status', and a ticket types like 'Feature', 'Bug', 'Severe Bug', 'Idea' etc. would be much more helpful.

Also it would mean nice filtering options in list and kanban view.

**Comment by nickbe** [comment]
Works great. Thanks and closed.

**Comment by nickbe** [comment]
I think this issue can be closed :)
