### ISSUE TITLE
Laravel question

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#29]
when making changes to public/css/tiny.css... how to I create the public/build/ccs files?

**Comment by satrun77** [comment]
CSS files should not be changed manually. 

You can changes the LESS files (except for bootstrap files) then compile JS and LESS with gulp

Command
$ gulp

Production command 
$ gulp --production

**Comment by nickbe** [comment]
ok, took my a while to figure out how to install node and gulp in windows.
Thanks
