### ISSUE TITLE
Moving items in kanban

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#31]
In my own version moving items within the kanban board does not change the status. After reload it's like nothing has been moved.

Is this just my version or is this also in the current develop version?

**Comment by satrun77** [comment]
The code in develop branch works fine for me. Update your code and try again

**Comment by nickbe** [comment]
Very strange. I already have the latest branch and it didn't work.
But now.... well.. it just works. Why I don't know, but what would a project be without its mysteries :)
