### ISSUE TITLE
Tag access and visibilty enhancement

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#37]
#### Better Tag handling:

1. a user role dropdown:
> User-Level needed to set and view this tag: [ Admin | Manager | Developer | User ]
> Message Level for each Tag: Minimum User Role to receive a message when tag has been set.

I think users should only be able to use tags according to this user-level. This gives us the possibility to let the administrator assign type tags like "Internal" or "Information", or prevent a developer from tagging an issue as "resolved". or letting a user set 'bug','feature','idea' but not 'knowledge'.

btw. This would also provide a simple way of having a tiny knowledgebase. Only thing needed would be a new main menu item which shows tickets of certain ticket types. 

- A new global option should give the user the ability to select the ticket types to show under knowledge.

Example: 'Basic Knowledge', 'Advanced Knowledge' (both would be ticket types)
As of now there's a build in status **closed**. There should be an additional build in status **canned**. All tickets with the status 'canned' should also be available under Knowledge.

Then show all those tickets as usual - project independend - searchable - and without all the status-changes in history - only the ticket and it's comments.

2. An additional private | public Switch per ticket.
> Visibilty: [private|public] 

- Users with 'User' and 'Developer' shouldn't see those tickets at all.

**Comment by nickbe** [comment]
I'll try to implement this next.

**Comment by satrun77** [comment]
Fixed in #77

**Comment by nickbe** [comment]
Definetely closed.
