### ISSUE TITLE
Possible bug in tags

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#40]
I can click on the tag group name and edit this - which let's me do some real nonsense here.
Doesn't make any sense to me and should be completely removed. :)

**Comment by satrun77** [comment]
Not sure I understood what you mean here

**Comment by nickbe** [comment]
![screenshot_24](https://cloud.githubusercontent.com/assets/10890765/14161851/20111b5c-f6e7-11e5-9487-0d4a7cfc92c6.jpg)

In the latest pull request I prevented the user from editing the groups themselves.
Now they can only edit the tags for each group.

**Comment by satrun77** [comment]
User can still accessing the page. Also, why do you think the  user should not be able to change the group details?

**Comment by nickbe** [comment]
First, the group does not use a color - where would it be displayed? 
Also the three group names should be in the standard language files.

And if you change the group for the group, which I did, you end up loosing that group.
I think everything that can mess up things should be prevented.

**Comment by satrun77** [comment]
Change applied as part of #41

**Comment by nickbe** [comment]
Thanks and closed.
