### ISSUE TITLE
Editing tickets should be more consistent

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#41]
I think when I'm creating/editing a ticket should always be displayed with seperated fields.
(depending of the user role of course)

A dropdown for the status-tag (allow only one status at a time - this is also necesssary for kanban)
A second field which might allow to combine statuses, but I also think that there should be only one type tag per ticket. The same goes for the resolution field. The easier the better. 

The storage goes probably into the same database field. But I think that's not a bad thing at all.

**Comment by nickbe** [comment]
Instead of a status tag dropdown, I think now that a simpele tag cloud line would be better. Thats only one click. Like this:

open      construction        review         **released**        closed

Seeing it this way it would somehow correlate to the kanban view - except it always shows all the possible states.

Resolution by dropdown is good. As is issue type.

**Comment by satrun77** [comment]
> Resolution by dropdown is good. As is issue type.

Do you mean you want a second field to select the resolution tag?

**Comment by nickbe** [comment]
yes. I think it would be easier this way. If you have a tag line like now - with predefined values - then you have to know what you could type and you never see all possible values. 

A simple dropdown is easier to handle - you don't have to think - but if necessary you can always write a last comment before closing the ticket and explain some resolution in depth.

**Comment by nickbe** [comment]
Ok, if you take a look at the attached pics... this is basically what I suggest:

For CREATING TICKETS:
![tiny-screen-01](https://cloud.githubusercontent.com/assets/10890765/14142166/49b1e684-f684-11e5-9463-98b7cdc6dfa8.jpg)

and for EDITING TICKETS: (If you're more than just a user)
![tiny-screen-02](https://cloud.githubusercontent.com/assets/10890765/14142177/5bcb8dfc-f684-11e5-8d58-d46baa3966de.jpg)

**Comment by satrun77** [comment]
Ah ok. I like this idea.

**Comment by nickbe** [comment]
Hey this looks very good now. Nicely done!
Thanks and closed.
