### ISSUE TITLE
Archived projects

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#44]
I tried to find out how I can archive a project. Would be nice if it worked.
Any idea how to do this?

**Comment by satrun77** [comment]
Edit the project to archive it

**Comment by nickbe** [comment]
Oh boy ;)  Status: open|archived.
I must have overlooked this a thousand times.

**Comment by nickbe** [comment]
This is just a matte of a minor interface improvement in later versions.
In this case I would prefer a button [ **Archive this project | Reactivate this project **] and a nice label showing the current state to the dropdown.

**Comment by nickbe** [comment]
Closed for now.
