### ISSUE TITLE
Deploying tinyissue

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#47]
Which folders do I need to deploy a production version to the server?
(I don't want to compile anything there, just run tinyissue)

I suppose /tests/ is not needed?
And node_modules?

**Comment by satrun77** [comment]
You don't need tests or node_modules. 

You do need to run composer install to generate the vendor files.

**Comment by nickbe** [comment]
Thanks. And I suppse when updating I simply replace everything exept storage?

**Comment by nickbe** [comment]
....env seems to need the complete path to the database. Can you make it accept the relative path also?

**Comment by nickbe** [comment]
.... another question: Can't I simply cooy the vendor files from my local version?

**Comment by satrun77** [comment]
> .... another question: Can't I simply cooy the vendor files from my local version?
You can try. vendor is third party dependencies that should not be copied but generated with composer. However, I have been thinking about creating a compressed file for each release that includes all of the required files including the vendor and excluding the development files such as tests. Then users who do not know how to use composer can just copy and past the app and modify the .env file to start using the site.

**Comment by nickbe** [comment]
I think that's a very good idea. It took me some time to find out about composer myself. So I guess having an all-in-one deployment package is a fine thing for unexperienced users. I'll create something on the website which points to the latest "light release" as well as to some "complete release". 

btw. I don't want to write everything into github. Is there a way to contact you per mail? 
IF that's ok... then simply write a quick note to nick@nickbe.net.

**Comment by nickbe** [comment]
I successfully copied my local github clone to the webserver path.
The public/.htaccess has to contain a rule:

`RewriteBase /`

Shouldn't this be added generally?

Problem remaining is: I cannot log in because tinyisse claims that user/password does not match.
But the database in storage is the same I use locally for development. Any idea what's wrong here?

**Comment by satrun77** [comment]
> Should the APPENV be set to 'production' instead of 'local'?
It should be local, unless you are deploying the app then changes to production.

> `RewriteBase /` Shouldn't this be added generally?
There is no need for this. This line changes teh base URL to `/` if you install the site in a subdirectory. the only thing can do here is update the .htaccess to match Laravel latest version: 
 https://github.com/laravel/laravel/blob/master/public/.htaccess

**Comment by nickbe** [comment]
I installed tinyissue in the root folder of a subdomain. If I don't add RewriteBase tinyissue won't run here.
So I suggest that you add some comment in the readme file. I had that problem many times before and it drives you nuts if you don't know what to do :)

**Comment by satrun77** [comment]
Can you please explain more what is not working. The app is based on laravel if the htaccess does not work then laravel does not work too.

**Comment by nickbe** [comment]
As soon as I leave out "RewriteBase /", I receive an error:

 I think we're lost.
Server Error: 404 (Not Found) 

After adding RewriteBase everything works as expected :)

**Comment by satrun77** [comment]
Ah ok. That's because your subdomain configuration does not set the public root directory to `/` then you need to have `RewriteBase /` in your htaccess file.

There is no harm from adding that line to htaccess

**Comment by nickbe** [comment]
i think we simply mention this in the installation section of the readme then :)
Closed.

**Comment by nickbe** [comment]
I'm reopening this because of the infamous 'RewriteBase /'
Both my local installations and my linux instances need to have this option to work.

Since I tend to forget this, wondering why the site won't work - I'd like to ask if you could just add 'RewriteBase to your default /public/.htaccess? Would it be of any harm to users?

**Comment by nickbe** [comment]
Thanks and closed.
