### ISSUE TITLE
Running tiny issue in iFrame

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#50]
I read that this should work, but there has to be an exception configured somewhere in the laravel config. 

For example: iOS provides an option to put a weblink directly as an icon on your screen. So by clicking the icon you'll get a fullscreen browser with an app like appearance, and no URL line or buttons. So it feels like more like an app and you the effective screen size is bigger due to the missing browser controls.

If I try to run tiny issue as a fullscreen app - the problem seems that laravel constantly reloads complete pages - therefore any link inside tiny issue tries to open the next page back in the standard browser.

Now I've read that one possible solution to this is to simply run the app inside an iFrame and load this iframe_index.php instead of the index.php. This should effectively prevent opening the browser with each click, always staying inside the iFrame.

Is it possible to allow the app to run inside a simple iFrame like this:

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Page Title</title>

    <style type="text/css" media="screen">

        body,
        html {
            width: 100%;
            height: 100%;
            overflow: hidden;
        }

        * {
            padding: 0;
            margin: 0;
        }

        iframe {
            width: 100%;
            height: 100%;
            overflow: hidden;
            border: none;
        }
    </style>

</head>
<body>

    <iframe src="index.php" scrolling="no"></iframe>

</body>
</html>
```

**Comment by satrun77** [comment]
The app should works in fullscreen. Some links works, others don't. 

Some links about the issue;
http://stackoverflow.com/questions/6429492/how-do-you-keep-an-iphone-ipad-web-app-in-full-screen-mode
http://stackoverflow.com/questions/2898740/iphone-safari-web-app-opens-links-in-new-window

I will try the jquery plugin: https://github.com/mrmoses/jQuery.stayInWebApp

**Comment by nickbe** [comment]
Thanks

**Comment by nickbe** [comment]
I think this js lib prevents resizing for mobiles and drag / drop for kanban board.
Sorry!

**Comment by nickbe** [comment]
Whe I try stayinWebApp then iOS calls a new safari windows anyways.
But when I test the following js snippet it actually works.

I'll give it thorough test. There seems to be difference in the way the two routines handle the problem, although I'm not sure why it doesn't work in the first place.

```
$( document ).on( "click","a", function( e ){
	e.preventDefault();
	document.location.href = $(this).attr('href');
});

```
I inserted this at the top of app.js. From what i can tell on my iPhone here it works.
