### ISSUE TITLE
Side colors in kanban items should represent the ticket type

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#51]
The sidebar of kanban items have currently the color of the ticket status - but it should be the color of the ticket-type (bug, issue, feature and so on) instead. 

![screenshot_25](https://cloud.githubusercontent.com/assets/10890765/14335633/1fb3b77a-fc5d-11e5-86b9-1883493efbee.jpg)

**Comment by nickbe** [comment]
I tried to locate the problem for hours now.
Giving up now. This is too frustrating. Could you point me in the right direction here?

**Comment by satrun77** [comment]
I have fixed this issue and deployed to develop branch

**Comment by nickbe** [comment]
Cool, but I'd really like to know what you changed :)

**Comment by satrun77** [comment]
The query fetches issues with status tags only. Change it to return all tags but group by status and then filter out the first type tag to use the color.

**Comment by nickbe** [comment]
Ok I checked the code. I guess it's straightforward if you wrote the code :). 
But now that I review what you've changed it made perfect sense to me.
