### ISSUE TITLE
Make database path relative

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#54]
I'd like to be able to use
DB_DATABASE=storage/tinyissue.sqlite
instead of
DB_DATABASE=D:\CMS\tinyissue\storage\tinyissue.sqlite

btw. TinyIssue runs perfectly on windows with just PHP installed:
PHP -S 127.0.0.1 -t tinyissue\public

I think this should definetely be mentioned in the install documentation.

**Comment by satrun77** [comment]
> PHP -S 127.0.0.1 -t tinyissue\public
is for development only not production.

**Comment by nickbe** [comment]
Well basically yes. But if you just need a local installation you can just do that. And a colleague of mine is using it that way right now, because he is at a customers site with his notebook and no wifi or other internet connection ;).

**Comment by nickbe** [comment]
But using relative paths and a default database name would make installation easier. That's what I actually meant.

**Comment by nickbe** [comment]
Closed
