### ISSUE TITLE
Tags Buttons should be unique and deselected when clicked again

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#55]
If you click on a resolution, type or status the previous selection should be deselected.
Clicking twice on the same tag should also deselect the tag.

**Comment by nickbe** [comment]
Just noticed... the previous selection is deselected, but the deselection is not shown immediately.

**Comment by satrun77** [comment]
Not sure what you mean by not shown immediately. The buttons are radios buttons styled as button.

**Comment by nickbe** [comment]
Yes I noticed this now. But when changing the state of a radio button all fields remain clicked. 
Like this :)

![screenshot_6](https://cloud.githubusercontent.com/assets/10890765/14798127/50dd05c6-0b36-11e6-8c52-e881eff16fb3.png)

**Comment by satrun77** [comment]
Ah ok. It is possible an issue from the buttons on the creating a new project. The buttons are checkboxes instead of radios. Its possible that the javascript is conflicting here.

**Comment by nickbe** [comment]
Looks fine now. 
Thanks and closed.
