### ISSUE TITLE
Allow sorting of tags in tag management.

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#57]
The tags should then be shown in the selected order.

![screenshot_4](https://cloud.githubusercontent.com/assets/10890765/14794528/eaced4b4-0b24-11e6-9515-1cd2184eff6f.png)

In this case the correct order would be 
**NEW** - **FRIDGE** (which I don't alwaysw show in kanban) - **OPEN** - **DISCUSS** - **WORKING** - **READY** - **RELEASED** - **CLOSED** - **CANNED** (also actually not shown, but I wanted to show my status tags)

btw. When will a ticket vanish from kanban? (Since the status **open** is always added)

**Comment by satrun77** [comment]
Drag & drop buttons from project add/edit form.

**Comment by nickbe** [comment]
Hey Mohamed,
sortable tag buttons?! - even better than I wished for :)
Thanks and closed.
