### ISSUE TITLE
Kanban fields are not shown as selected when creating new project

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#59]
They are however selected. But you can't see it until you save and reopen.

**Comment by satrun77** [comment]
Can I have screenshots.

**Comment by nickbe** [comment]
Sure. Here. I just clicked 3 tag fields while creating a project.

![screenshot_5](https://cloud.githubusercontent.com/assets/10890765/14798083/14aefa78-0b36-11e6-8e07-ae0b9754c794.png)

**Comment by nickbe** [comment]
Currently creating a new project seems broken.

**Comment by satrun77** [comment]
Any error messages?

**Comment by nickbe** [comment]
Whoops, looks like something went wrong.
2/2 ErrorException in Project.php line 121: Undefined variable: selectTags (View: U:\LABSITE-Github\www\tinyissue\resources\views\projects\new.blade.php)

**Comment by satrun77** [comment]
This error fixed in develop branch

**Comment by nickbe** [comment]
Thanks!
