### ISSUE TITLE
Bug in tags management

### ISSUE THREAD

**Issue by satrun77** [satrun77/tinyissue#6]
I think there's a bug in the tags management.
If I want to add a tag to the status then no matter if I select the status group there's always a new tag group created, but not a new group value.

**Comment by nickbe** [comment]
I'm afraid something's still not right.
I tried to insert a new tag in "Status"
After creating a new tag and pressing Update I was left with only the tag groups: "Resolution" and "Type" left. The Group "Status" is gone.

**Comment by satrun77** [comment]
Thats sound strange. Can you post a screenshot also, the version of Tinyissue

**Comment by nickbe** [comment]
btw. the group 'status' magically reappeared meanwhile. But I assure you it wasn't there anymore.
Well I keep an eye on that.
