### ISSUE TITLE
Assigning tickets

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#63]
Every user should be able to assign/reassign tickets to other users 
with an equal user role or below.

Managers -> ASSIGN -> other managers, developers, users.
Developers -> ASSIGN -> other developers, users.

and so on....

**Comment by satrun77** [comment]
Prefer to keep the team work of the project open with no restriction :)

**Comment by nickbe** [comment]
Fine by be :)
Maybe I'll put it back on my xmas wishlist some day....
