### ISSUE TITLE
Bug in comment when editing / deleting

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#68]
Both functions do not work at the moment. 
Editing results in a "Whoops..." error and deleting in a simple "not found".

**Comment by nickbe** [comment]
Thanks. Now it works.

Is there a way to delete an attached file from a comment. I think currently we have to delete the complete comment to get rid of a sinlg image or attachment. Do you think you could provide a simple [X] per attachment to remove them?

**Comment by satrun77** [comment]
I may change how attachments are added to the issue. I don't like how its currently working. It can create many orphans files.

I prefer not to add more features to that part for now.

**Comment by nickbe** [comment]
Well currently the bad thing is that I cannot delete my attachments anymore. Upload a wrong image and you have to delete the whole comment.
