### ISSUE TITLE
How can I add columns to the kanban view?

### ISSUE THREAD

**Issue by satrun77** [satrun77/tinyissue#7]
No matter what I enter in the columns field of a project, nothing seems to be added.

**Comment by satrun77** [comment]
Unable to replicate this issue. Will close for now. Can open new issue if this still a problem.

**Comment by nickbe** [comment]
Hey :)

I was trying to have the following kanban fields:  

Unconfirmed | Open | Working | Solved | Reviewed | Closed

But I'm still unable to create those. Could you explain how I would do this?
Thanks.
Nick

**Comment by satrun77** [comment]
- It will always starts with Open and ends with Closed.
- Create new tags with under the group status for Working | Solved | Reviewed.
- Edit your project type 'W', then a dropdown box must appears with all tags starting with 'W'. Select Working. Same for other tags.
- Save your changes. The Kanban view must displays columns for each of the tags. 

Can you post a screenshot. It would make it easier to see what is going on wrong.

**Comment by nickbe** [comment]
Ok. I updated to the latest version. (6 days ago)  and i finally got the status for kanban working :)
If I may, I'd like to make some suggestions:

- I think the currently selected project should be shown by default as a kanban view
- A doubleclick on the kanban items could jump directly into the items details
- kanban should show either my own, but also ALL items in the current project. 
- And it should therefore also be selectable directly from the dashboard.

**Comment by satrun77** [comment]
That is great it is working for you. Thanks for the suggestions. I will add each of the suggestion as separate issue.

**Comment by nickbe** [comment]
i think I made a mistake here. The kanban view should be selectable from within the 'project' view.
So when looking at the list of issues for one project - it should be possible to switch to kanban - similar to what you have now when viewing 'Your issues'
