### ISSUE TITLE
Open and Closed tag handling

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#70]
Right now **open** and **closed** are special tags as far as I understand.

In the screenshot you can see that a ticket has the status **CONSTRUCTION** as well as **OPEN**

![screenshot_37](https://cloud.githubusercontent.com/assets/10890765/14828152/01b0ced2-0be6-11e6-8c1e-5fd0514f550f.jpg)

- First of all I'd actually rather only see **CONSTRUCTION** because as long as the ticket is not closed, all other states automatically mean that it's open.

- Renaming the **OPEN** tag currently results in an error when creating a ticket. So I suggest to use it invisibly and internally only. The same goes for **CLOSED**. 

- The Internally set color for **CLOSED** should simply be light gray and it should only be displayed when searching for tickets and displaying closed ones.

- I suggest to remove **OPEN** from the status selectors since it is always selected anyway. 

- **Closed** should remain when creating a ticket. Maybe I want to create a ticket and then close it at the same time. So that's ok.

- Neither in the Kanban view nor anywhere else should the status **OPEN** be visible at all, since all other states beside **CLOSED** automatically means it's open.

**Comment by nickbe** [comment]
Here we have the following process for our tickets:

1. Ticket arrives: Status **NEW** (has yet to be reviewed to determine if it's actually worth investigating
2. Then the tickets run thru all necessary steps (each a different status)
3. In the end the ticket is closed and the ticket-type is set to **KNOWLEDGE** if we think it's worth something.

**Comment by satrun77** [comment]
Fixed in #77
