### ISSUE TITLE
Another crash

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#72]
This:

![screenshot_38](https://cloud.githubusercontent.com/assets/10890765/14830180/926f1b78-0bef-11e6-9d8d-c86a9e6c81ae.jpg)

currently results in this:

![screenshot_39](https://cloud.githubusercontent.com/assets/10890765/14830195/a668fbf8-0bef-11e6-8f4e-05708e78b94e.jpg)

**Comment by nickbe** [comment]
This happens when editing issues

**Comment by satrun77** [comment]
I'm unable to replicate this. Did you rename the open or the closed tag?

**Comment by nickbe** [comment]
Yes and no. I renamed it to xxxOpen and then renamed it back to **open**. After that the other error was gone. How can I see if everything else is ok?

**Comment by nickbe** [comment]
I think I found the problem. I created a ticket with no **open** status. However this happened I don't know. Maybe I did this when **open** was renamed to **xxopen**.

However when I edit this ticket and select **open** then I receive no error when saving, but also nothing is changed and after reloading the ticket it still has no **open** status.

**Comment by nickbe** [comment]
I think the best thing would be if I could just delete this ticket ;)

But also renaming of **open** and **closed** should be forbidden. See

**Comment by nickbe** [comment]
Closed because it's probably a direct result of a currupt record.
