### ISSUE TITLE
Open Close Tag Problem

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#73]
You just deactivated the open/close tags, but you still show them in the kanbanboard.

I meant they should be treated invisibly and that a ticket should be at least in one other state.
(Which it normally is anyway since it is always **open** and something else

For example:   [ Unconfirmed ]   [  Queued ]    [ Working ]   [ Ready ]   [ Released ]
So the **open** AND the first state [ unconfirmed ]  should always be default when creating a ticket.

After closing a ticket the ticket should not be visible on the kanban anymore.

-> For now could you please make **open** / **close** available in the project configuration so that I can deselect them in the current kanban views.

**Comment by satrun77** [comment]
Fixed in #77
