### ISSUE TITLE
Deleting attachments in comments

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#74]
Currently attachments in comments cannot be deleted.

**Comment by nickbe** [comment]
Seems to work. Everything else is more redesign than function.
Thanks and closed.

**Comment by nickbe** [comment]
Well I think as for messaging this is perfectly ok. 
I'd rather prefer not to get overloaded with messages except important ones. 

Is there another location where attachments could be deleted?

**Comment by satrun77** [comment]
> Is there another location where attachments could be deleted?
On creating a new issue you can upload attachement

**Comment by nickbe** [comment]
Ah ok. So at least I can delete the attachments later after saving.
