### ISSUE TITLE
Error when trying to create a ticket for certain projects

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#75]
If the project has no kanban field selected, then [ + New Issue ] throws an error:

exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Method Tinyissue\Form\Former\Fields\RadioButton::__toString() must not throw an exception' in tinyissue\app\Extensions\Html\FormBuilder.php:0

**Comment by satrun77** [comment]
Yeah. I have changed this recently. What you do you think is best option.

1) Limit status in issue to statues defined in kanban only.
2) Limit status in issue to statues defined in kanban. if no statuses selected, then fallback to all statuses in the site,
3) Show all statues in the site regardless to what we have in kanban.

**Comment by nickbe** [comment]
Basically Issues should show ALL statuses in the site (except for **open** and **closed**)
these two should be handled automatically and differently.

The kanban board should then be able to show only an excerpt of the statuses.
And this is of course different from project to project.

But since projects can be very different ( which is something I just experienced )
there can be lots of status tags in time.

So, the best thing would probably be to have 2 status configurations in a project.

1. "Select status fields for this project." (select statuses from all the statuses in the site)
2. "Select kanban fields for this project (which is a bit tricky since it would depend on 1. and you would need to select from the project-dependend statuses in 1.)

But it would be the right way to do it.

You could select you statuses for the current project from all the sites statuses:

[ **New** ]  [ unconfirmed ]  [  **Todo** ]    [  **Construction** ]     [  **Testing** ]   [ Ready ]  [  Production ]   [ **Certified** ]

And then select the kanban status fields from the status subset  above:
[ New ] [ **Todo** ]  [ **Construction** ]  [ **Testing** ]  [ Certified ]

In this example I only want to see issues after I declared them [ **Todo** ] and they should be invisible to the board after I declared them [ Certified ]

**Comment by nickbe** [comment]
I'm slowly getting there while Laravel kicks me in the back now and then. ;)

Now every tag has a limit user role. Example status: [ **Discussion** ]

If the manager sets a ticket status to **DISCUSSION** and for example the developer has no right to handle that status, then the only status the developer sees is **DISCUSSION** (and therefore he cannot change it).

Meanwhile in the kanban view the column **DISCUSSION** is not available to him at all.

Now Managers/Admins can handle this ticket until they push it back into the system and set a new state. 

Now I have to do the same type and resolution.

**Comment by nickbe** [comment]
I close this. The remaining problem will get a sperate ticket
