### ISSUE TITLE
System option to allow users a kanban view

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#80]
There should then be a new option "Enable user kanban view" to decide if the users can switch to "My Issues" -> kanban or not. 

This also means he must not be able to drag/drop items in the kanban view.

**Comment by nickbe** [comment]
Some additional thought on this:
Why not make a system setting: "Kanban View limit" and let the administrator decide which role is needed to be able to use the kanban view at all. If we set the role to "user" then no drag drop should be possible for a user.

**Comment by satrun77** [comment]
Currently this can be done for all users. 
User role: can see the kanban view. Drag and drop animation works but user cannot change status.

**Comment by nickbe** [comment]
What issues do they see? The ones they posted?

**Comment by satrun77** [comment]
your issue should show assigned issues to the users. Current the kanban view show all issues in project!

**Comment by nickbe** [comment]
For me users can be testers, clients, and so on. I would want them to see only the issues they themselve created. No matter if they look at the kanban or the list. That way they can check their tickets, but There are many issues I regard as internal only. Like bugs I don't want to share with normal users.

What about a setting (globally or maybe even per project): "Users can see: <their own issues|all issues in project>?

**Comment by nickbe** [comment]
Sorry the post was truncated:

A setting
Users can see: own issues / all projext issues

**Comment by satrun77** [comment]
currently that view does not work right for users. will have to fix this and consider the setting option.

**Comment by nickbe** [comment]
Okay. I'll write a github entry and for all we talked about tonight.

**Comment by nickbe** [comment]
This works but I think you should restrict the projects issue list too.

I think we should do this depending on the private/public flag of the project (which we already have). Since this flag already does something similar to the project itself.

Anyway I think it's necessary to prevent normal users from viewing all issues.

**Comment by satrun77** [comment]
Create github issue for each  change, so it easy to manage. :)

**Comment by nickbe** [comment]
ok. done.
