### ISSUE TITLE
Seperate location of database from storage folder

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#82]
To prevent the current database from being overwritten when updating.

**Comment by satrun77** [comment]
How do you upgrade the application. The database file is not tracked in git. See https://github.com/satrun77/tinyissue/blob/master/.gitignore#L21

**Comment by nickbe** [comment]
Well, since my provider has his issues with composer installs I simply copy the files to the server and run 'composer update --with-dependencies' and 'php artisan migrate' after that.

The issue not vital, but it's nagging me. So if there are too many changes involved then don't bother.

**Comment by satrun77** [comment]
Database can by anywhere you want. By default it's under storage. 

That's why the path is not relative in .env file.

**Comment by nickbe** [comment]
Ah ok - didn't realize that. Then forget this and I also close the 'relative database path ticket'
