### ISSUE TITLE
Default status for new tickets needed

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#85]
Since no normal user has rights to change the status of a ticket here, the status is always NULL when creating a new ticket.

But if I want the status to be set to, for example 'NEW' I would need a systemwiede 'Default status' setting.

Then my ticket status is always 'NEW' for users with no right to change the status. 

When entereing many tickets at once as a manager, I have the same problem. 
It would help to have the status set to a default value.

I would even suggest having different default statuses per user role:
In my case this would be 'new/unconfirmed' for users, 'Open' for Managers... and so on...

**Comment by satrun77** [comment]
By default new issues are with status New. Issue visible in open tab and if you open the issue, you will see the label "new"

**Comment by nickbe** [comment]
Ok now I'm confused. I have my own tag 'NEW' in the tags list. How does Tinyissue know that this is the first tag?

**Comment by satrun77** [comment]
Ok I see. There should be a tag from the status group to be chosen to be the default first tag to be auto selected when new issue added. This tag can be anything an admin select.

**Comment by nickbe** [comment]
Exactly! That would be great

**Comment by nickbe** [comment]
I'm afraid my english is not always perfect when it comes to describing these things :)

**Comment by nickbe** [comment]
Seems that the new default status is not yet selected when creating a new ticket.
