### ISSUE TITLE
Update assigne selector in project/ticket after adding user to project users

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#87]
When adding a user to a project any selector on the right is not immediately updated.
Is this possible as an ajax call?

**Comment by satrun77** [comment]
Not sure what you mean here.

**Comment by nickbe** [comment]
If you're assigning a user to a project then any open form drop down on the right side is not immediately updated.

**Comment by nickbe** [comment]
I suggest moving "adding users to projects" away from the left sidebar.

It' easy this way, but has it's problems since the results can only be used after reloading the page to the right.
