### ISSUE TITLE
Cannot delete tags anymore

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#88]
Trying to delete the last type tag results in a 404 error.

**Comment by satrun77** [comment]
unable to replicate this issue

**Comment by nickbe** [comment]
Let me take a look at the database. I still have this error.

**Comment by nickbe** [comment]
record #26 seems to look completely normal.

ID   parent  name    color    group    created    updated   rolelimit
25	1	Review	        #d3b95f	0	2016-05-09 17:37:57	2016-05-09 17:38:34	2
26	2	Nonsense	#ffffff	0	2016-05-09 19:07:21	2016-05-09 19:21:28	1

Delete calls the URL http://issues.ai-support.de/administration/tag/26/delete
But when I try to delete it this is what I get:

I think we're lost.
Server Error: 404 (Not Found)

**Comment by nickbe** [comment]
Wait ... i cannot delete any of the tags.
I installed the latest develop version.

**Comment by satrun77** [comment]
If Laravel cannot find the route, it is most likely the route cache need to be refreshed. You can clear it with:
`php artisan route:clear`

**Comment by nickbe** [comment]
I just tried that but this didn't make a difference. Still the same error.

**Comment by nickbe** [comment]
php artisan route:list shows me that there's no route like 'administration/tag/{tag}/delete/' but instead
2 x 'administration/tag/{tag}/edit'.
Does that mean anything?

**Comment by satrun77** [comment]
The edit route is correct.

Maybe you have older version of develop branch. the delete route is here: https://github.com/satrun77/tinyissue/blob/develop/app/Providers/RouteServiceProvider.php#L159

**Comment by nickbe** [comment]
That's weird. I definetely have the correct RouteServiceProvider.php - the line is here.

**Comment by nickbe** [comment]
All right. After deleting everythingm, a fresh install and restoring the .env and my database file I can again delete tags. Any idea what causes this problem? Can we prevent this somehow in the future?

**Comment by satrun77** [comment]
This is laravel cache you can clear it with above command or delete cache directory

**Comment by nickbe** [comment]
I used these commands (several times), but it didn't work.

artisan cache:clear
artisan route:clear
artisan route:cache

Then I reinstalled from scratch. After that it was ok and the route was listed in the route list.

btw: When reinstalling I forgot to save the uploads :/ so I lost all my images - Should I always leave the storage folder as it is?

**Comment by nickbe** [comment]
Anyway it works and I suppose this is only a problem when updating - which we should adress in a later version. Maybe there'll be an auto update sometimes. 
Closed for now
