### ISSUE TITLE
Problem with unintended logout after closing an issue

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#90]
After closing an issue I click on the open tickets link in the left sidebar, but instead of showing the tickets I'm required to login.

**Comment by satrun77** [comment]
unable to replicate this issue. It is possible that your session expired at the same time.

**Comment by nickbe** [comment]
I could do this multiple times this morning.
closed an issue - forced to relogin - over and over again.
At one point I pressed F5 after seeing the dashboard and was immediately thrown out again to the login.

**Comment by satrun77** [comment]
I still can't replicate this issue!

**Comment by nickbe** [comment]
Mmmmh. I tried to do this today but couldn't 
Please file this under "to investigate later"
