### ISSUE TITLE
PROJECTS: Readonly option when granting project access to user

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#91]
After adding a user to a project (currently in the left sidebar) there should be 
a simple dropdown after each active user to grant either [ Member or Observer ] access for the current project. The dropdown should only be visible for 'Managers/Admins'

**Comment by satrun77** [comment]
This issue/change is unclear. Currently the roles are:

The user role is the Observer role. They can only view issues and create new issues.
The developer, & manager are the members that can modify the issue.

**Comment by nickbe** [comment]
I thought this thru and I think it's not the correct solution for what I intended anymore. The current way is better and I'd rather close this at least for now. Maybe one day when I thought of something better I'll repost a new issue. Until then I think the way it is implemented now is perfect enough.
Thanks and closed.
