### ISSUE TITLE
Show resolution tags in kanban items

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#95]
Just that

**Comment by satrun77** [comment]
I need more details. How do you want the show the resolution tags?

**Comment by nickbe** [comment]
Well I'd say the same way as usual - a small colored tag pill somewhere inside each kanban item.

**Comment by satrun77** [comment]
I still not sure how you want to display this. 

If we have another column for all resolution tags, then this column is going to be long, and therefore similar issue to https://github.com/satrun77/tinyissue/pull/77#issuecomment-216081831

**Comment by nickbe** [comment]
Oh I see. I didn't mean a column. I meant a simple small tag inside each kanban item card.
Something like this:

[ #99 My Kanban Item ]
[ Nick 2 months ago * ]
[                   (FIXED)  ]

**Comment by satrun77** [comment]
Ah ok. I see.

**Comment by nickbe** [comment]
Currently I cannot view kanban anymore. See #106

**Comment by nickbe** [comment]
Solved. Checked and closed.
Thanks :)
