### ISSUE TITLE
Set random generic password as default for users

### ISSUE THREAD

**Issue by nickbe** [satrun77/tinyissue#98]
When creating a new user we could use a button to create a random password for this user. A random password should also be set as default when the user is created.

**Comment by nickbe** [comment]
Currently the password field is not shown at all when creating a user. 
This seems odd and I think it would be best to show the password fields when creating the user in the first place.

Additionally there should always be a simple button to create a random password for the user. Best title I can think of is simply [ Set random passwort ]. If there's already a password set then there should be a simple request to make sure setting a new password is intentionally.

**Comment by satrun77** [comment]
The password is randomly generated on creating a new user, then an email is sent to the user with this temporary password: https://github.com/satrun77/tinyissue/blob/master/app/Model/Traits/User/CrudTrait.php#L52

**Comment by nickbe** [comment]
Oh. I didn't know that :) is that new?

**Comment by satrun77** [comment]
It's from the original project.

**Comment by nickbe** [comment]
:) ok. Then maybe it would be good to show some stars or a message which explains that. In my case I'd wish I could simply enter passwords manually.

**Comment by nickbe** [comment]
Even with a password quality check.
Perfect ! Thanks.
